# Copyright 2018-2022 NXP
#
# SPDX-License-Identifier: Apache-2.0
#
# #############################################################
# This file is generated using a script
# #############################################################
#
IF(
    SSS_HAVE_APPLET_A71CH
     OR SSS_HAVE_APPLET_A71CL
     OR SSS_HAVE_APPLET_A71CH_SIM
     OR SSS_HAVE_APPLET_SE05X_A
     OR SSS_HAVE_APPLET_SE05X_B
     OR SSS_HAVE_APPLET_SE05X_C
     OR SSS_HAVE_APPLET_SE05X_L
     OR SSS_HAVE_APPLET_SE051_UWB
     OR SSS_HAVE_APPLET_SE051_H
     OR SSS_HAVE_APPLET_AUTH
     OR SSS_HAVE_APPLET_SE050_E
     OR SSS_HAVE_APPLET_LOOPBACK
)
    SET(SSS_HAVE_APPLET ON)
ELSE()
    SET(SSS_HAVE_APPLET OFF)
ENDIF()
IF(
    SSS_HAVE_APPLET_SE05X_A
     OR SSS_HAVE_APPLET_SE05X_B
     OR SSS_HAVE_APPLET_SE05X_C
     OR SSS_HAVE_APPLET_SE051_UWB
     OR SSS_HAVE_APPLET_SE051_H
     OR SSS_HAVE_APPLET_AUTH
     OR SSS_HAVE_APPLET_SE050_E
)
    SET(SSS_HAVE_APPLET_SE05X_IOT ON)
ELSE()
    SET(SSS_HAVE_APPLET_SE05X_IOT OFF)
ENDIF()
IF(SSS_HAVE_MBEDTLS_ALT_SSS OR SSS_HAVE_MBEDTLS_ALT_A71CH OR SSS_HAVE_MBEDTLS_ALT_PSA)
    SET(SSS_HAVE_MBEDTLS_ALT ON)
ELSE()
    SET(SSS_HAVE_MBEDTLS_ALT OFF)
ENDIF()
IF(SSS_HAVE_HOSTCRYPTO_MBEDTLS OR SSS_HAVE_HOSTCRYPTO_OPENSSL OR SSS_HAVE_HOSTCRYPTO_USER)
    SET(SSS_HAVE_HOSTCRYPTO_ANY ON)
ELSE()
    SET(SSS_HAVE_HOSTCRYPTO_ANY OFF)
ENDIF()
IF(SSS_HAVE_FIPS_SE050 OR SSS_HAVE_FIPS_140_2 OR SSS_HAVE_FIPS_140_3)
    SET(SSS_HAVE_FIPS ON)
ELSE()
    SET(SSS_HAVE_FIPS OFF)
ENDIF()

IF(SSS_HAVE_HOST_FRDMK64F AND SSS_HAVE_APPLET)
    IF(NOT (SSS_HAVE_SMCOM_SCI2C OR SSS_HAVE_SMCOM_T1OI2C OR SSS_HAVE_SMCOM_T1OI2C_GP1_0 OR SSS_HAVE_SMCOM_PN7150))
        MESSAGE(
            FATAL_ERROR
                "One of 'SSS_HAVE_SMCOM_SCI2C, SSS_HAVE_SMCOM_T1OI2C, SSS_HAVE_SMCOM_T1OI2C_GP1_0, SSS_HAVE_SMCOM_PN7150' must be set[for SSS_HAVE_HOST_FRDMK64F AND SSS_HAVE_APPLET]."
        )
    ENDIF()
ENDIF(SSS_HAVE_HOST_FRDMK64F AND SSS_HAVE_APPLET)

IF(SSS_HAVE_HOST_EVKMIMXRT1060 AND SSS_HAVE_APPLET)
    IF(NOT (SSS_HAVE_SMCOM_SCI2C OR SSS_HAVE_SMCOM_T1OI2C OR SSS_HAVE_SMCOM_T1OI2C_GP1_0))
        MESSAGE(
            FATAL_ERROR
                "One of 'SSS_HAVE_SMCOM_SCI2C, SSS_HAVE_SMCOM_T1OI2C, SSS_HAVE_SMCOM_T1OI2C_GP1_0' must be set[for SSS_HAVE_HOST_EVKMIMXRT1060 AND SSS_HAVE_APPLET]."
        )
    ENDIF()
ENDIF(SSS_HAVE_HOST_EVKMIMXRT1060 AND SSS_HAVE_APPLET)

IF(WithSSS_A71CH)
    MESSAGE(WARNING "Keyword 'WithSSS_A71CH' is deprecated.")
ENDIF()

IF(WithSSS_A71CL)
    MESSAGE(WARNING "Keyword 'WithSSS_A71CL' is deprecated.")
ENDIF()

IF(WithSSS_SE050)
    MESSAGE(WARNING "Keyword 'WithSSS_SE050' is deprecated.")
ENDIF()

IF(WithSSS_A71CH_SIM)
    MESSAGE(WARNING "Keyword 'WithSSS_A71CH_SIM' is deprecated.")
ENDIF()

IF(WithSSS_SE050_EAR_CL)
    MESSAGE(WARNING "Keyword 'WithSSS_SE050_EAR_CL' is deprecated.")
ENDIF()

IF(WithSSS_TESTCOUNTERPART)
    MESSAGE(WARNING "Keyword 'WithSSS_TESTCOUNTERPART' is deprecated.")
ENDIF()

IF(Applet_SE05X_Ver_01_01_00)
    MESSAGE(WARNING "Keyword 'Applet_SE05X_Ver_01_01_00' is deprecated.")
ENDIF()

IF(Applet_SE05X_Ver_01_02_00)
    MESSAGE(WARNING "Keyword 'Applet_SE05X_Ver_01_02_00' is deprecated.")
ENDIF()

IF(Applet_SE05X_Ver_02_00_00)
    MESSAGE(WARNING "Keyword 'Applet_SE05X_Ver_02_00_00' is deprecated.")
ENDIF()

IF(Applet_SE05X_Ver_02_01_00)
    MESSAGE(WARNING "Keyword 'Applet_SE05X_Ver_02_01_00' is deprecated.")
ENDIF()

IF(WithSMCOM_JRCP)
    MESSAGE(WARNING "Keyword 'WithSMCOM_JRCP' is deprecated.")
ENDIF()

IF(WithSMCOM_SOCKET)
    MESSAGE(WARNING "Keyword 'WithSMCOM_SOCKET' is deprecated.")
ENDIF()

IF(WithSSS_TestCounterPart)
    MESSAGE(WARNING "Keyword 'WithSSS_TestCounterPart' is deprecated.")
ENDIF()

# Version checks GTE - Greater Than Or Equal To
IF(SSS_HAVE_APPLET_SE05X_IOT)
    IF(SSS_HAVE_SE05X_VER_07_02)
         SET(SSS_HAVE_SE05X_VER_GTE_07_02 ON)
         SET(SSS_HAVE_SE05X_VER_GTE_06_00 ON)
         SET(SSS_HAVE_SE05X_VER_GTE_03_XX ON)
    ENDIF()

    IF(SSS_HAVE_SE05X_VER_06_00)
         SET(SSS_HAVE_SE05X_VER_GTE_07_02 OFF)
         SET(SSS_HAVE_SE05X_VER_GTE_06_00 ON)
         SET(SSS_HAVE_SE05X_VER_GTE_03_XX ON)
    ENDIF()

    IF(SSS_HAVE_SE05X_VER_03_XX)
         SET(SSS_HAVE_SE05X_VER_GTE_07_02 OFF)
         SET(SSS_HAVE_SE05X_VER_GTE_06_00 OFF)
         SET(SSS_HAVE_SE05X_VER_GTE_03_XX ON)
    ENDIF()

ELSE() #SSS_HAVE_APPLET_SE05X_IOT
     SET(SSS_HAVE_SE05X_VER_GTE_03_XX OFF)
     SET(SSS_HAVE_SE05X_VER_GTE_06_00 OFF)
     SET(SSS_HAVE_SE05X_VER_GTE_07_02 OFF)
ENDIF() #SSS_HAVE_APPLET_SE05X_IOT
